check gmtool version for feature in gradle plugin
You need to call checkAvailability(feature) in when calling a gmtool feature
that is available only in recent gmtool release.
The method will throm an exception to the user

```
* What went wrong:
Execution failed for task ':simple:genymotionLaunch'.
> com.genymotion.tools.GMToolException: GMTool command failed. You need GMTool version 2.9.0 (current version is 2.8.0)
```